name: Continuous Integration
on: push #trigger event
env: #define environment variables
  DB_Name: test 
  DB_User: root 
  DB_Pass: strongRoots@911
jobs:
  run_code_checks: #setup base container
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start 
          sudo mysql -e 'ALTER USER "${{env.DB_User}}"@"localhost" IDENTIFIED BY ${{env.DB_Pass}}";' -uroot -proot
          sudo mysql -e 'CREATE DATABASE ${{env.DB_Name}};' -u${env.DB_User} -p${env.DB_Pass}
      - name: Checkout Repo Code #checkout code on our repo
        uses: actions/checkout@v2 
      - name: Set up GoLang
        uses: actions/setup-go@vs 
        with: 
          go-version: 1.20.1
      - name: Run linting
        run: |
         go fmt ./...
         go vet ./...
      - name: Run tests 
        run: go test 
      

